### ISSUE TITLE
TIGASE_HOME is not set

### ISSUE THREAD

**Issue by ruitobe** [YiChat/IM_Server_YiChat#2]
Tried to start tigase sever by tigase start, but reported error message: 
TIGASE_HOME is not set.

seems there is no related tigase-server*.jar file?

**Comment by tangloong** [comment]
跑起来了、连接不上
Loading component: ws2s :: componentInfo{Title=Tigase XMPP Server, Version=7.1.0-b4379/8ed39c0c (2017-01-30/19:29:59), Class=tigase.server.websocket.WebSocketClientConnectionManager}
2018-10-22 16:39:41.533 [main]             ConfigurationCache.store()         WARNING:  Dumping server configuration to: etc/config-dump.properties
== Mon Oct 22 16:39:41 CST 2018 Server finished starting up and (if there wasn't any error) is ready to use

2018-10-22 16:41:34.278 [Timer-1]          RequestHandler$2.run()             WARNING:  request processing time exceeded! for id = 3
2018-10-22 16:42:55.376 [ConnectionOpenThread]  SocketThread.<clinit>()       WARNING:  9 socketReadThreads started.
2018-10-22 16:42:55.381 [ConnectionOpenThread]  SocketThread.<clinit>()       WARNING:  9 socketWriteThreads started.

**Comment by tangloong** [comment]
连接上了不能加好友 Spark 不能登录 APP可以 奇怪，

**Comment by qingshi688** [comment]
> 连接上了不能加好友 Spark 不能登录 APP可以 奇怪，

哥们我也遇到了这个问题。。TIGASE_HOME is not set   请教下怎么解决的呢

**Comment by CHNPeterWang** [comment]
> 连接上了不能加好友 Spark 不能登录 APP可以 奇怪，

老铁，能否交流一下，我的spark能聊天，但是App就是连不上

**Comment by CHNPeterWang** [comment]
> > 连接上了不能加好友 Spark 不能登录 APP可以 奇怪，
> 
> 哥们我也遇到了这个问题。。TIGASE_HOME is not set 请教下怎么解决的呢

环境变量里加上就行

**Comment by CHNPeterWang** [comment]
我的APP一直报这个错误

2019-02-22 16:55:29.953 21912-22023/com.htmessage.yichatopen I/MessageService: connectXmppconnect()--->e--->No response received within reply timeout. Timeout was 5000ms (~5s). Used filter: No filter used or filter was 'null'.
2019-02-22 16:55:29.954 21912-22023/com.htmessage.yichatopen W/System.err: org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). Used filter: No filter used or filter was 'null'.
2019-02-22 16:55:29.954 21912-22023/com.htmessage.yichatopen W/System.err:     at org.jivesoftware.smack.SynchronizationPoint.checkForResponse(SynchronizationPoint.java:253)
2019-02-22 16:55:29.954 21912-22023/com.htmessage.yichatopen W/System.err:     at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWait(SynchronizationPoint.java:146)
2019-02-22 16:55:29.954 21912-22023/com.htmessage.yichatopen W/System.err:     at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWaitOrThrow(SynchronizationPoint.java:125)
2019-02-22 16:55:29.954 21912-22023/com.htmessage.yichatopen W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:857)
2019-02-22 16:55:29.954 21912-22023/com.htmessage.yichatopen W/System.err:     at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:364)
2019-02-22 16:55:29.954 21912-22023/com.htmessage.yichatopen W/System.err:     at com.htmessage.sdk.service.MessageService$1.run(Unknown Source:6)
2019-02-22 16:55:29.954 21912-22023/com.htmessage.yichatopen W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-02-22 16:55:29.956 21912-22025/com.htmessage.yichatopen W/AbstractXMPPConnection: Connection closed with error
    org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
    <stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1015)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:956)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:971)
        at java.lang.Thread.run(Thread.java:764)
2019-02-22 16:55:29.956 21912-22025/com.htmessage.yichatopen I/MessageService: connectionListener:--->connectionClosedOnError--->e---->host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
    <stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>

**Comment by tangloong** [comment]
> > 连接上了不能加好友 Spark 不能登录 APP可以 奇怪，
> 
> 老铁，能否交流一下，我的spark能聊天，但是App就是连不上

我现在源码都找不到了，我记得 我记了怎么解决来着  我找一找，好像需要在某个文件里面添加

**Comment by CHNPeterWang** [comment]
> > > 连接上了不能加好友 Spark 不能登录 APP可以 奇怪，
> > 
> > 
> > 老铁，能否交流一下，我的spark能聊天，但是App就是连不上
> 
> 我现在源码都找不到了，我记得 我记了怎么解决来着 我找一找，好像需要在某个文件里面添加

感谢，麻烦找一下了

**Comment by cocoyes** [comment]
> Tried to start tigase sever by tigase start, but reported error message:
> TIGASE_HOME is not set.
> 
> seems there is no related tigase-server*.jar file?

hello,I also encountered this problem, how do you solve it?

**Comment by hantu85** [comment]
Looking at the source code of this project you need to build this YiChat server before you will be able to use it. It contains old source code of Tigase XMPP Server. If you would like to try original Tigase XMPP Server in the newest version,  then you will find Tigase XMPP Server project page at https://tigase.tech/projects/tigase-server and full documentation for Tigase is available at https://docs.tigase.net/tigase-server/snapshot/Administration_Guide/html/

**Comment by jiachengll** [comment]
出现TIGASE_HOME is not set.  
需要到/scripts/tigase.sh   88行    修改tigase-server

**Comment by 280462111** [comment]
> tigase-server

修改成什么??

**Comment by liwei3927** [comment]
/opt/tigase-server-7.1.3-b4482/jars/   添加tigase-server-7.1.3-b4482.jar
